### ISSUE TITLE
Code used to generate charts

### ISSUE THREAD

**Issue by ashim95** [mubasharaak/ChartFC_chartBERT#2]
Hi @mubasharaak ,

Thank you for releasing the dataset and the code. 

I wanted to ask if you can share the code you used to generate the chart images? Additionally, what pytorch and python versions did you use?

Thanks,

**Comment by mubasharaak** [comment]
Hi Ashim,

Sure, I'll upload the files for chart creation to the repo. 

I used the following versions: 
Python 3.10.6.
Pytorch 1.12.
